name: gha-workflow-test
on: [push, pull_request]
jobs:
  gha-job-lint:
    name: Lint
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.6'
      - name: Bundle
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
      - name: Lint
        run: bundle exec rubocop

  # The test job is a matrix of ruby/rails versions.
  gha-job-test:
    name: Ruby ${{ matrix.ruby }}
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        ruby: [ '2.6', '2.7', '3.0', '3.1' ]
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Test
        run: bundle exec rspec

      - name: Coverage
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}